### PR TITLE
Create dependency-includer-script.php

### PR DESCRIPTION
**Pull request by gamebits**
Adds a missing file, necessary for uninstallation. Closes https://github.com/Automattic/newspack-content-converter/issues/100.

### CODE REVIEW

**Review by iuravic — CHANGES_REQUESTED** [review]
This plugin uses Composer autoloading which automatically requires all dependencies wo/ manually specifying each one of them, e.g. [here](https://github.com/Automattic/newspack-content-converter/blob/master/newspack-content-converter.php#L17).

What seems to be the issue here? Let's see how we can fix it by using Composer.

**Comment by gamebits** [comment]
> What seems to be the issue here?

@iuravic See #100 for details.

**Comment by iuravic** [comment]
> > What seems to be the issue here?
> 
> @iuravic See #100 for details.

Thanks for reminding me, @gamebits.

I believe the fix should be the following, to replace [this line](https://github.com/Automattic/newspack-content-converter/blob/6646651ccc0caafb8d80bfb84f6a9c5a46274aec/uninstall.php#L11) with (e.g. as is also used [here](https://github.com/Automattic/newspack-content-converter/blob/6646651ccc0caafb8d80bfb84f6a9c5a46274aec/uninstall.php#L11))
```
require __DIR__ . '/vendor/autoload.php';
```

This should fix the uninstaller, I believe. Would you be up to try this and commit it to this PR, or should I?

**Comment by gamebits** [comment]
Closing in favor of #104.

**Pull request closed without merging**
